// Code generated by capnpc-go. DO NOT EDIT.

package zaphttp_capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0x82ef9c51fc9be8ce

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0x82ef9c51fc9be8ce, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Header) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Header) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Header) Values() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s Header) HasValues() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Header) SetValues(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewValues sets the values field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Header) NewValues(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type Request capnp.Struct

// Request_TypeID is the unique identifier for the type Request.
const Request_TypeID = 0xb2063b47a28c074a

func NewRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Request(st), err
}

func NewRootRequest(s *capnp.Segment) (Request, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Request(st), err
}

func ReadRootRequest(msg *capnp.Message) (Request, error) {
	root, err := msg.Root()
	return Request(root.Struct()), err
}

func (s Request) String() string {
	str, _ := text.Marshal(0xb2063b47a28c074a, capnp.Struct(s))
	return str
}

func (s Request) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Request) DecodeFromPtr(p capnp.Ptr) Request {
	return Request(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Request) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Request) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Request) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Request) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Request) Method() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Request) HasMethod() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Request) MethodBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Request) SetMethod(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Request) Target() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Request) HasTarget() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Request) TargetBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Request) SetTarget(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Request) Proto() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Request) HasProto() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Request) ProtoBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Request) SetProto(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Request) Headers() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return Header_List(p.List()), err
}

func (s Request) HasHeaders() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Request) SetHeaders(v Header_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewHeaders sets the headers field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s Request) NewHeaders(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s Request) Body() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s Request) HasBody() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Request) SetBody(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

func (s Request) Trailer() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return Header_List(p.List()), err
}

func (s Request) HasTrailer() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Request) SetTrailer(v Header_List) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewTrailer sets the trailer field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s Request) NewTrailer(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}

// Request_List is a list of Request.
type Request_List = capnp.StructList[Request]

// NewRequest creates a new list of Request.
func NewRequest_List(s *capnp.Segment, sz int32) (Request_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6}, sz)
	return capnp.StructList[Request](l), err
}

// Request_Future is a wrapper for a Request promised by a client call.
type Request_Future struct{ *capnp.Future }

func (f Request_Future) Struct() (Request, error) {
	p, err := f.Future.Ptr()
	return Request(p.Struct()), err
}

type Response capnp.Struct

// Response_TypeID is the unique identifier for the type Response.
const Response_TypeID = 0xab7e8c4a7b2a9bff

func NewResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Response(st), err
}

func NewRootResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5})
	return Response(st), err
}

func ReadRootResponse(msg *capnp.Message) (Response, error) {
	root, err := msg.Root()
	return Response(root.Struct()), err
}

func (s Response) String() string {
	str, _ := text.Marshal(0xab7e8c4a7b2a9bff, capnp.Struct(s))
	return str
}

func (s Response) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Response) DecodeFromPtr(p capnp.Ptr) Response {
	return Response(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Response) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Response) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Response) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Response) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Response) Status() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s Response) SetStatus(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s Response) Reason() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Response) HasReason() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Response) ReasonBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Response) SetReason(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Response) Proto() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Response) HasProto() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Response) ProtoBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Response) SetProto(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Response) Headers() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Header_List(p.List()), err
}

func (s Response) HasHeaders() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Response) SetHeaders(v Header_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewHeaders sets the headers field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s Response) NewHeaders(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Response) Body() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Response) HasBody() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Response) SetBody(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Response) Trailer() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return Header_List(p.List()), err
}

func (s Response) HasTrailer() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Response) SetTrailer(v Header_List) error {
	return capnp.Struct(s).SetPtr(4, v.ToPtr())
}

// NewTrailer sets the trailer field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s Response) NewTrailer(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(4, l.ToPtr())
	return l, err
}

// Response_List is a list of Response.
type Response_List = capnp.StructList[Response]

// NewResponse creates a new list of Response.
func NewResponse_List(s *capnp.Segment, sz int32) (Response_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 5}, sz)
	return capnp.StructList[Response](l), err
}

// Response_Future is a wrapper for a Response promised by a client call.
type Response_Future struct{ *capnp.Future }

func (f Response_Future) Struct() (Response, error) {
	p, err := f.Future.Ptr()
	return Response(p.Struct()), err
}

type Frame capnp.Struct
type Frame_Which uint16

const (
	Frame_Which_request  Frame_Which = 0
	Frame_Which_response Frame_Which = 1
)

func (w Frame_Which) String() string {
	const s = "requestresponse"
	switch w {
	case Frame_Which_request:
		return s[0:7]
	case Frame_Which_response:
		return s[7:15]

	}
	return "Frame_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Frame_TypeID is the unique identifier for the type Frame.
const Frame_TypeID = 0xda62522904e66ee9

func NewFrame(s *capnp.Segment) (Frame, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Frame(st), err
}

func NewRootFrame(s *capnp.Segment) (Frame, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Frame(st), err
}

func ReadRootFrame(msg *capnp.Message) (Frame, error) {
	root, err := msg.Root()
	return Frame(root.Struct()), err
}

func (s Frame) String() string {
	str, _ := text.Marshal(0xda62522904e66ee9, capnp.Struct(s))
	return str
}

func (s Frame) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Frame) DecodeFromPtr(p capnp.Ptr) Frame {
	return Frame(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Frame) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Frame) Which() Frame_Which {
	return Frame_Which(capnp.Struct(s).Uint16(0))
}
func (s Frame) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Frame) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Frame) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Frame) Request() (Request, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != request")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return Request(p.Struct()), err
}

func (s Frame) HasRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Frame) SetRequest(v Request) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRequest sets the request field to a newly
// allocated Request struct, preferring placement in s's segment.
func (s Frame) NewRequest() (Request, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewRequest(capnp.Struct(s).Segment())
	if err != nil {
		return Request{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Frame) Response() (Response, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != response")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return Response(p.Struct()), err
}

func (s Frame) HasResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Frame) SetResponse(v Response) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResponse sets the response field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s Frame) NewResponse() (Response, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewResponse(capnp.Struct(s).Segment())
	if err != nil {
		return Response{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Frame_List is a list of Frame.
type Frame_List = capnp.StructList[Frame]

// NewFrame creates a new list of Frame.
func NewFrame_List(s *capnp.Segment, sz int32) (Frame_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Frame](l), err
}

// Frame_Future is a wrapper for a Frame promised by a client call.
type Frame_Future struct{ *capnp.Future }

func (f Frame_Future) Struct() (Frame, error) {
	p, err := f.Future.Ptr()
	return Frame(p.Struct()), err
}
func (p Frame_Future) Request() Request_Future {
	return Request_Future{Future: p.Future.Field(0, nil)}
}
func (p Frame_Future) Response() Response_Future {
	return Response_Future{Future: p.Future.Field(0, nil)}
}

const schema_a3d4b2e80f1c5a7e = "x\xda\xc4\x93\xbdk\x14Q\x14\xc5\xcfyo&k\x91" +
	"\xcd\xecc\xb6\xb0\x10baa\x82\x91D\x1b\x89\xc5J" +
	"\xf03 \xe4\xa5\x11ld\xe2>\\!\xbb3\xce\xcc" +
	"\xba\xa8\x90\x05\xeb\x94\x16\x86$\x90\xf8\x01\xa2\xddba" +
	"\xc4\x80\xda\xd8Y\xa5\xf2\x0f\x90X\xf9\x0f\x88#o?" +
	"%nj\xbb\x99;g\xeey\xefw\xcf\x9dn\xf0\x82" +
	"3\x93\xff\" \xf4qw$\xfb\xba\xbf\xfeKo\xfc" +
	"|\x0c\xe51[\xb9y\xcc\xdbo\xed=\x87+r\x80" +
	"\x7f\x8d-_\xd3>]g\x03\xcc\xb2\xf5\xc9G\xf3\xab" +
	"+o\xa0=\xfe-v\xadd\x87\x9f\xfdOV|v" +
	"\x977\x08f\xf3\xb9\xd5gW\xce\x8f\xb4\x0et\x1e\xb1" +
	"\xe2\x09\xf9\xde\x9f\x91V<%\xdb\xe2\x1f\xb5\xef\xce\xc4" +
	"\xe2\xd2\xb7\x03\xad/1'\x00\x7f\xcdy\xedo;\xf6" +
	"\xc7M\xa7\x81\xa9\xeca\x10\xdd\xaa\xa4i\xc4\xd3\xb7\x83" +
	"\xa8\x16\xcd^\x1d7A\xd9\xc4\x0b\xa4>\"\x1d\xc0!" +
	"\xa0&&\x01}BRO\x0b*\xb2H[\x9c\x9a\x05" +
	"\xf4II}Q\xd0\xab\x05U\xc3Q\x08\x8e\x82\xa5\xfb" +
	"\xc1r\xdd$\x1c\x03\x17$\xdb\xd51\xb0\xef$\xbaN" +
	"\x8b&\x89\xc2Zb`\xbd\x8e\xf6\xbd\xd6l\xdb'\x92" +
	"zK\xb0g\xb5ikO%\xf5\x0bA%X\xa4\x00" +
	"\xd4\xf6\x19@oH\xeaW\x82J\x8a\"%\xa0^\xce" +
	"\x01zKR\x7f\x10T\x8e,\xd2\x01\xd4\x8e=\xfe[" +
	"I\xfdQP\xb9N\x91.\xa0v\xad\xf2\x9d\xa4\xde\x13" +
	",%i\x90\xd6\x13\xe6 \x98\x03K\xb1\x09\x92\xb0\xd6" +
	"\xbb\xcfx\x14\x87i\xd8{kV\xda\x80\xfa\xd7+\x0c" +
	"\xe6\x0e\xda\xa2\xb7\x14\x96\x1f0\x0f\xc1<\xd8L\xe3\xe0" +
	"\xee\xb2\x89\x0fU\xff3\x80\xc5\x92\xb9W7Iz8" +
	"\x155\x1c\x8b\x18\x86E\x0e\xc3\xe2\x0c\xc3\xe2\x0e\xc1R" +
	"5i%,\xf7\xe7\x9a\x06\xf1\x1d\x93\xfe\x1f,\x97\xbd" +
	"8\xa8\x9an,G\xb3\xac\x93\xcb\xb9A.\xf3\xfc\x9d" +
	"u\x839\x0f\xe8S\x92\xfa\x9c`3\xee\xd0da\xb0" +
	"D \x0b`\x16\xf7\xf2\x07\xb00X\xc8\xce\xd7?\x01" +
	"\x00\x00\xff\xff\xacC\xe6\x10"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a3d4b2e80f1c5a7e,
		Nodes: []uint64{
			0x82ef9c51fc9be8ce,
			0xab7e8c4a7b2a9bff,
			0xb2063b47a28c074a,
			0xda62522904e66ee9,
		},
		Compressed: true,
	})
}
